// <auto-generated />
using System;
using InvoiceAuditor.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceAuditor.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413111804_AddLineItems")]
    partial class AddLineItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InvoiceAuditor.API.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExtractedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExtractedDueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExtractedInvoiceNumber")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ExtractedSubTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ExtractedTaxAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ExtractedTotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ExtractedVendorABN")
                        .HasColumnType("longtext");

                    b.Property<string>("ExtractedVendorAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("ExtractedVendorName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFlaggedForFraud")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentDetails")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StoredFilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("InvoiceId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("InvoiceAuditor.API.Models.InvoiceItem", b =>
                {
                    b.Property<int>("InvoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InvoiceItemId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.HasKey("InvoiceItemId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("InvoiceAuditor.API.Models.InvoiceItem", b =>
                {
                    b.HasOne("InvoiceAuditor.API.Models.Invoice", null)
                        .WithMany("LineItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceAuditor.API.Models.Invoice", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
